type Season {
  year: Int!
  url: String!
}

input NewSeasonInput {
  year: Int!
  url: String!
}

input UpdateSeasonInput {
  url: String
}

input FilterSeasonInput {
  year: Int
  url: String
}

extend type Query {
  seasons(skip: Int, limit: Int, filter: FilterSeasonInput): [Season]!
  season(year: Int!): Season!
}

extend type Mutation {
  newSeason(input: NewSeasonInput!): Season!
  updateSeason(year: Int!, input: UpdateSeasonInput!): Season!
  removeSeason(year: Int!): Season!
}
