type Driver {
  driverId: Int!
  driverRef: String!
  number: Int
  code: String
  forename: String
  surname: String
  dob: Date
  nationality: String
  url: String
}

input NewDriverInput {
  driverId: Int!
  driverRef: String!
  number: Int
  code: String
  forename: String
  surname: String
  dob: Date
  nationality: String
  url: String
}

input UpdateDriverInput {
  driverId: Int
  driverRef: String
  number: Int
  code: String
  forename: String
  surname: String
  dob: Date
  nationality: String
  url: String
}

extend type Query {
  drivers: [Driver]
  driver(id: ID!): Driver!
}

extend type Mutation {
  newDriver(input: NewDriverInput!): Driver!
  updateDriver(input: UpdateDriverInput!): Driver!
  removeDriver(id: ID!): Driver!
}
