type Driver {
  driverId: Int!
  driverRef: String!
  number: Int
  code: String
  forename: String
  surname: String
  dob: Date
  nationality: String
  url: String
  driverStandings(
    skip: Int
    limit: Int
    filter: FilterDriverStandingInput
  ): [DriverStanding]
  qualifyings(
    skip: Int
    limit: Int
    filter: FilterQualifyingInput
  ): [Qualifying]
  pitStops(skip: Int, limit: Int, filter: FilterPitStopInput): [PitStop]
  lapTimes(skip: Int, limit: Int, filter: FilterLapTimeInput): [LapTime]
  results(skip: Int, limit: Int, filter: FilterResultInput): [Result]
}

input NewDriverInput {
  driverId: Int!
  driverRef: String!
  number: Int
  code: String
  forename: String
  surname: String
  dob: Date
  nationality: String
  url: String
}

input UpdateDriverInput {
  driverRef: String
  number: Int
  code: String
  forename: String
  surname: String
  dob: Date
  nationality: String
  url: String
}

input FilterDriverInput {
  driverId: Int
  driverRef: String
  number: Int
  code: String
  forename: String
  surname: String
  dob: Date
  nationality: String
  url: String
}

extend type Query {
  drivers(skip: Int, limit: Int, filter: FilterDriverInput): [Driver]
  driver(filter: FilterDriverInput!): Driver!
}

extend type Mutation {
  newDriver(input: NewDriverInput!): Driver!
  updateDriver(driverId: ID!, input: UpdateDriverInput!): Driver!
  removeDriver(driverId: ID!): Driver!
}
