type Race {
  raceId: Int!
  year: Int!
  round: Int!
  circuitId: Int!
  circuit: Circuit!
  name: String!
  date: Date!
  time: String
  url: String
}

input NewRaceInput {
  raceId: Int!
  year: Int!
  round: Int!
  circuitId: Int!
  name: String!
  date: Date!
  time: String
  url: String
}

input UpdateRaceInput {
  year: Int
  round: Int
  circuitId: Int
  name: String
  date: Date
  time: String
  url: String
}

input FilterRaceInput {
  raceId: Int
  year: Int
  round: Int
  circuitId: Int
  name: String
  date: Date
  time: String
  url: String
}

extend type Query {
  races(skip: Int, limit: Int, filter: FilterRaceInput): [Race]!
  race(raceId: ID!): Race!
}

extend type Mutation {
  newRace(input: NewRaceInput!): Race!
  updateRace(raceId: ID!, input: UpdateRaceInput!): Race!
  removeRace(raceId: Int!): Race!
}
