type Status {
  statusId: Int!
  status: String!
}

input NewStatusInput {
  statusId: Int!
  status: String!
}

input UpdateStatusInput {
  status: String
}

input FilterStatusInput {
  statusId: Int
  status: String
}

extend type Query {
  statuses(skip: Int, limit: Int, filter: FilterStatusInput): [Status]!
  status(statusId: Int!): Status!
}

extend type Mutation {
  newStatus(input: NewStatusInput!): Status!
  updateStatus(statusId: Int!, input: UpdateStatusInput!): Status!
  removeStatus(statusId: Int!): Status!
}
