type Qualifying {
  qualifyId: Int!
  raceId: Int!
  race(filter: FilterRaceInput): Race
  driverId: Int!
  driver(filter: FilterDriverInput): Driver
  constructorId: Int!
  constructor(filter: FilterConstructorInput): Constructor
  number: Int!
  position: Int
  q1: String
  q2: String
  q3: String
}

input NewQualifyingInput {
  qualifyId: Int!
  raceId: Int!
  driverId: Int!
  constructorId: Int!
  number: Int!
  position: Int
  q1: String
  q2: String
  q3: String
}

input UpdateQualifyingInput {
  raceId: Int
  driverId: Int
  constructorId: Int
  number: Int
  position: Int
  q1: String
  q2: String
  q3: String
}

input FilterQualifyingInput {
  qualifyId: Int
  raceId: Int
  driverId: Int
  constructorId: Int
  number: Int
  position: Int
  q1: String
  q2: String
  q3: String
}

extend type Query {
  qualifyings(
    skip: Int
    limit: Int
    filter: FilterQualifyingInput
  ): [Qualifying]!
  qualifying(filter: FilterQualifyingInput!): Qualifying!
}

extend type Mutation {
  newQualifying(input: NewQualifyingInput!): Qualifying!
  updateQualifying(qualifyId: ID!, input: UpdateQualifyingInput!): Qualifying!
  removeQualifying(qualifyId: ID!): Qualifying!
}
