type Constructor {
  constructorId: Int!
  constructorRef: String!
  name: String!
  nationality: String
  url: String!
  constructorStandings(
    skip: Int
    limit: Int
    filter: FilterConstructorStandingInput
  ): [ConstructorStanding]
  constructorResults(
    skip: Int
    limit: Int
    filter: FilterConstructorResultInput
  ): [ConstructorResult]
  qualifyings(
    skip: Int
    limit: Int
    filter: FilterQualifyingInput
  ): [Qualifying]
  pitStops(skip: Int, limit: Int, filter: FilterPitStopInput): [PitStop]
  results(skip: Int, limit: Int, filter: FilterResultInput): [Result]
}

input NewConstructorInput {
  constructorId: Int!
  constructorRef: String!
  name: String!
  nationality: String
  url: String!
}

input UpdateConstructorInput {
  constructorRef: String
  name: String
  nationality: String
  url: String
}

input FilterConstructorInput {
  constructorId: Int
  constructorRef: String
  name: String
  nationality: String
  url: String
}

extend type Query {
  constructors(
    skip: Int
    limit: Int
    filter: FilterConstructorInput
  ): [Constructor]!
  constructor(filter: FilterConstructorInput!): Constructor!
}

extend type Mutation {
  newConstructor(input: NewConstructorInput!): Constructor!
  updateConstructor(
    constructorId: ID!
    input: UpdateConstructorInput!
  ): Constructor!
  removeConstructor(constructorId: ID!): Constructor!
}
